out_dir: results
metric_best: mae
metric_agg: argmin
wandb:
  use: False
  project: ZINC
dataset:
  format: PyG-ZINC
  name: subset
  task: graph
  task_type: regression
  transductive: False
  node_encoder: True
  node_encoder_name: TypeDictNode+FLaGPE
  node_encoder_num_types: 28
  node_encoder_bn: False
  edge_encoder: True
  edge_encoder_name: TypeDictEdge
  edge_encoder_num_types: 4
  edge_encoder_bn: False
posenc_FLaGPE:
  enable: True
  dim_pe: 32
  k_hop: 5
  fragment_scheme: brics
  mlp_hidden: 64
  alpha_init: 0.5
  beta_init: 0.5
  num_layers: 10
  pass_as_var: False
train:
  mode: custom
  batch_size: 32
  eval_period: 1
  ckpt_period: 100
  auto_resume: True
  ckpt_clean: False
model:
  type: GPSModel
  loss_fun: l1
  edge_decoding: dot
  graph_pooling: add
gt:
  layer_type: GINE+Transformer
  layers: 10
  n_heads: 4
  dim_hidden: 64
  dropout: 0.0
  attn_dropout: 0.5
  layer_norm: False
  batch_norm: True
gnn:
  head: san_graph
  layers_pre_mp: 0
  layers_post_mp: 3
  dim_inner: 64
  batchnorm: True
  act: relu
  dropout: 0.0
  agg: mean
  normalize_adj: False
optim:
  clip_grad_norm: True
  optimizer: adamW
  weight_decay: 1e-5
  base_lr: 0.001
  max_epoch: 2000
  scheduler: cosine_with_warmup
  num_warmup_epochs: 50
