out_dir: results
metric_best: accuracy
metric_agg: argmax

wandb:
  use: False
  project: gtblueprint

dataset:
  format: PyG-Citation
  name: Citeseer
  task: node
  task_type: classification
  transductive: True
  node_encoder: False
  edge_encoder: False

posenc_LapPE:
  enable: False

train:
  mode: custom
  batch_size: 32
  eval_period: 1
  ckpt_period: 100

model:
  type: SANTransformer
  loss_fun: cross_entropy
  edge_decoding: dot
  graph_pooling: mean

gt:
  layers: 4
  n_heads: 8
  dim_hidden: 64
  full_graph: True
  gamma: 1e-5
  dropout: 0.1
  layer_norm: True
  batch_norm: False
  residual: True

gnn:
  head: san_graph
  layers_pre_mp: 0
  layers_post_mp: 2
  dim_inner: 64
  batchnorm: False
  act: relu
  dropout: 0.1
  agg: mean
  normalize_adj: False

optim:
  optimizer: adam
  weight_decay: 0.0
  base_lr: 0.001
  max_epoch: 100
  scheduler: reduce_on_plateau
  reduce_factor: 0.5
  schedule_patience: 10
  min_lr: 1e-6
